services:
  - type: web
    name: fetchnews-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false